### ISSUE TITLE
Progress Tracker

### ISSUE THREAD

**Issue by thomasgaozx** [thomasgaozx/udp-multiplayer#1]
## Stage 1

- No play animation, visual effects or ballistics
- [x] Implement snapshot structure
- [ ] Implement Client-Server game classes, alternative factories

## Stage 2

> Should have a functional system at this point

- [ ] Implement handshake and initialization
- [ ] Implement RPC Protocol and unit test
- [ ] Implement basic threading model
- [ ] Implement Fallback Mode Only
- No Interpolation or sophisticated snapshot system, server keeps 1 snapshot, and client gets updated

## Stage 3

- [ ] Advanced Snapshot System
- [ ] Implement Performant Mode

## Stage 4

- [ ] Perfect timing parameters
- [ ] Implement interpolation and prediction+correction
- [ ] Implement play animation
